In [5]:
#Consider the below code to answer further questions:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)
print(f"list_: {type(list_)}")
print(f"array_list: {type(array_list)}")
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#o print the data types of both the variables.

list_: <class 'list'>
array_list: <class 'numpy.ndarray'>


The data type of list_ is a Python list (list) and the data type of array_list is a NumPy array (numpy.ndarray). They are different data types.



Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
for i in list_:
    print(f"list_{type(list_)}")
            
for i in array_list:
    print(f"array list:{type(array_list)}")

list_<class 'list'>
list_<class 'list'>
list_<class 'list'>
list_<class 'list'>
list_<class 'list'>
array list:<class 'numpy.ndarray'>
array list:<class 'numpy.ndarray'>
array list:<class 'numpy.ndarray'>
array list:<class 'numpy.ndarray'>
array list:<class 'numpy.ndarray'>


In [9]:
#Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
array_list=np.array(object=list_,dtype=int)
array_list

array([1, 2, 3, 4, 5])

In [12]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

for i in list_:
    print(f"list_: {type(element)}")

for i in array_list:
    print(f"array_list: {type(element)}")


list_: <class 'numpy.int64'>
list_: <class 'numpy.int64'>
list_: <class 'numpy.int64'>
list_: <class 'numpy.int64'>
list_: <class 'numpy.int64'>
array_list: <class 'numpy.int64'>
array_list: <class 'numpy.int64'>
array_list: <class 'numpy.int64'>
array_list: <class 'numpy.int64'>
array_list: <class 'numpy.int64'>


In [15]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

print(f"Shape of num_array:{num_array.shape}")
print(f"Size of num_array:{num_array.size}")

Shape of num_array:(2, 3)
Size of num_array:6


Q5. Write a code to create a NumPy array of a 3x3 matrix containing zeros only, using a NumPy array creation function.

In [18]:
zero_matrix=np.zeros((3,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [19]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
